"""Add external_id to publications

Revision ID: 3f94e6ba6593
Revises: 
Create Date: 2025-05-10 04:06:46.417496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f94e6ba6593'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acquisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('supplier', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('acquisitions_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=False)

    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.drop_constraint('deliverables_milestone_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'milestones', ['milestone_id'], ['id'])

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.alter_column('quartile',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_constraint('milestones_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_constraint('project_members_project_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('project_members_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('publication_authors', schema=None) as batch_op:
        batch_op.drop_constraint('publication_authors_publication_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('publication_authors_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publications', ['publication_id'], ['id'])
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['id'])

    with op.batch_alter_table('publication_keywords', schema=None) as batch_op:
        batch_op.drop_constraint('publication_keywords_publication_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('publication_keywords_keyword_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publications', ['publication_id'], ['id'])
        batch_op.create_foreign_key(None, 'keywords', ['keyword_id'], ['id'])

    with op.batch_alter_table('publication_references', schema=None) as batch_op:
        batch_op.drop_constraint('publication_references_citing_publication_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('publication_references_referenced_publication_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publications', ['referenced_publication_id'], ['id'])
        batch_op.create_foreign_key(None, 'publications', ['citing_publication_id'], ['id'])

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('refresh_tokens_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('refresh_tokens_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('publication_references', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('publication_references_referenced_publication_id_fkey', 'publications', ['referenced_publication_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('publication_references_citing_publication_id_fkey', 'publications', ['citing_publication_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('publication_keywords', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('publication_keywords_keyword_id_fkey', 'keywords', ['keyword_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('publication_keywords_publication_id_fkey', 'publications', ['publication_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('publication_authors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('publication_authors_author_id_fkey', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('publication_authors_publication_id_fkey', 'publications', ['publication_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_members_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('project_members_project_id_fkey', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('milestones_project_id_fkey', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.alter_column('quartile',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=True)

    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('deliverables_milestone_id_fkey', 'milestones', ['milestone_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=False)

    with op.batch_alter_table('acquisitions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('acquisitions_project_id_fkey', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('supplier')
        batch_op.drop_column('category')
        batch_op.drop_column('purchase_date')

    # ### end Alembic commands ###
